processInterval: 10h
listen-address: 127.0.0.1:8080
database-path: ./gateway
min-amount: "0.003"
max-amount: "10"
receive-timeout: 168h
fee-percentage: 10
beneficiary-address: ADDRESS
wallet-rpc:
  url: http://127.0.0.1:18081/json_rpc
  username: username
  password: password
